const camObjects = [
  {
    "id": 1,
    "manufacturer": "Black Diamond",
    "model": "C3",
    "size": "000",
    "color": "gray",
    "lowMM": "7.8",
    "highMM": "12.9",
    "lowIN": "0.3",
    "highIN": "0.5",
    "weightG": "55",
    "weightOZ": "1.94",
    "Force (kN)": "4",
    "Force (lbf)": "899",
    "MSRP ($)": "$64.95"
  },
  {
    "id": 2,
    "manufacturer": "Black Diamond",
    "model": "C3",
    "size": "00",
    "color": "purple",
    "lowMM": "9",
    "highMM": "13.7",
    "lowIN": "0.35",
    "highIN": "0.54",
    "weightG": "57",
    "weightOZ": "2.00",
    "Force (kN)": "6",
    "Force (lbf)": "1349",
    "MSRP ($)": "$64.95"
  },
  {
    "id": 3,
    "manufacturer": "Black Diamond",
    "model": "C3",
    "size": "0",
    "color": "green",
    "lowMM": "10.7",
    "highMM": "15.8",
    "lowIN": "0.42",
    "highIN": "0.62",
    "weightG": "59",
    "weightOZ": "2.10",
    "Force (kN)": "7",
    "Force (lbf)": "1574",
    "MSRP ($)": "$64.95"
  },
  {
    "id": 4,
    "manufacturer": "Black Diamond",
    "model": "C3",
    "size": "1",
    "color": "red",
    "lowMM": "12",
    "highMM": "18.8",
    "lowIN": "0.47",
    "highIN": "0.74",
    "weightG": "62",
    "weightOZ": "2.20",
    "Force (kN)": "10",
    "Force (lbf)": "2248",
    "MSRP ($)": "$64.95"
  },
  {
    "id": 5,
    "manufacturer": "Black Diamond",
    "model": "C3",
    "size": "2",
    "color": "yellow",
    "lowMM": "14.2",
    "highMM": "22.6",
    "lowIN": "0.56",
    "highIN": "0.89",
    "weightG": "66",
    "weightOZ": "2.30",
    "Force (kN)": "10",
    "Force (lbf)": "2248",
    "MSRP ($)": "$64.95"
  },
  {
    "id": 6,
    "manufacturer": "Black Diamond",
    "model": "C4 (Pre-2019)",
    "size": "0.3",
    "color": "blue",
    "lowMM": "13.8",
    "highMM": "23.4",
    "lowIN": "0.54",
    "highIN": "0.92",
    "weightG": "75",
    "weightOZ": "2.65",
    "Force (kN)": "8",
    "Force (lbf)": "1798",
    "MSRP ($)": "$64.95"
  },
  {
    "id": 7,
    "manufacturer": "Black Diamond",
    "model": "C4 (Pre-2019)",
    "size": "0.4",
    "color": "gray",
    "lowMM": "15.5",
    "highMM": "26.7",
    "lowIN": "0.61",
    "highIN": "1.05",
    "weightG": "83",
    "weightOZ": "2.93",
    "Force (kN)": "10",
    "Force (lbf)": "2248",
    "MSRP ($)": "$64.95"
  }
];

export default camObjects;